### ISSUE TITLE
Confluent 3.3 support

### ISSUE THREAD

**Issue by vajda** [datamountaineer/stream-reactor#257]
Is there a release which works with Confluent 3.3 version?

**Comment by andrewstevenson** [comment]
Coming hopefully this week. A few issues to squeeze in first

**Comment by vajda** [comment]
Thanks for the info Andrew.

**Comment by jnguyenx** [comment]
I tried the release Release 0.3.0 with confluent 3.3.0, but I get an error when I try to boot up the kafka connect server with the Cassandra jar:

```
$ ./connect-distributed kafka-connect.properties 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/jnguyenx/workspace/kafka-connect-cassandra-0.3.0-3.3.0-all.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/jnguyenx/soft/confluent-3.3.0/share/java/kafka/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/jnguyenx/soft/confluent-3.3.0/share/java/kafka-connect-hdfs/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:380)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:221)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:198)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:159)
	at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:47)
	at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:63)
```

**Comment by andrewstevenson** [comment]
@jnguyenx How are you adding the connector to the classpath?

**Comment by jnguyenx** [comment]
I export the jar path as follow:
`export CLASSPATH="/home/jnguyenx/workspace/kafka-connect-cassandra-0.3.0-3.3.0-all.jar"`

**Comment by andrewstevenson** [comment]
set the plugins.path property in the connect-avro-distributed to use Connects classloader isolation.

**Comment by jnguyenx** [comment]
Thanks, it seems to work better now ;-)
I've put the additional jar in `confluent-3.3.0/share/java/kafka-connect-cassandra/`

**Comment by jnguyenx** [comment]
Hmm in fact I still have issues, the logging issue is gone, but now I get lots of `ClassNotFoundException`.
Can you tell me more about this `plugins.path` property? I grepped the confluent distribution but couldn't locate it.

**Comment by andrewstevenson** [comment]
Its on here http://docs.confluent.io/current/connect/userguide.html

**Comment by jnguyenx** [comment]
Awesome, this time I'm good to go. Thanks for the super fast replies!

**Comment by stheppi** [comment]
We would appreciate if you could star our repo :)

**Comment by vivek1739** [comment]
check your $CLASSPATH once.
It may be pointing to old gauva jars like in hadoop , hive etc.
Comment the old ones in CLASSPATH and add the confluent common and kafka jar location.
Then it will work
